### ISSUE TITLE
Using xDAI chain not working

### ISSUE THREAD

**Issue by Aeroxander** [ethereumjs/ethereumjs-monorepo#1033]
Using the xDAI chain gives a `Error HH604: Error running JSON-RPC server: Chain with ID 100 not supported` error in Hardhat

Original hardhat issue: https://github.com/nomiclabs/hardhat/issues/1008

**Comment by cgewecke** [comment]
@Aeroxander Could you provide some steps to reproduce this error (or a link to a public repo)?

Using HH's Greeter sample project and running the node as shown in the linked issue I see
```
$ npx hardhat node --fork https://rpc.xdaichain.com
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/

Accounts
========
etc...
```

When I run the tests, the node errors but doesn't mention common...
```
web3_clientVersion (2)
eth_chainId
eth_accounts
eth_chainId
eth_estimateGas
  Error: Invalid RpcBlockWithTransactions or null
      at codec.decode.fold (/Users/cgewecke/code/typechain-test/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/types.ts:8:11)
      at Left.fold (/Users/cgewecke/code/typechain-test/node_modules/io-ts/node_modules/fp-ts/lib/Either.js:113:16)
      at Object.decode (/Users/cgewecke/code/typechain-test/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/types.ts:6:30)
      at JsonRpcClient._perform (/Users/cgewecke/code/typechain-test/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/client.ts:230:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by alcuadrado** [comment]
I don't think this is caused by ethereumjs, but rather some of our validation logic being too strict.

**Comment by holgerd77** [comment]
I've just opened a PR to improve the custom chain support situation on `Common` at #1034, just to mention here.

I've not very much insights on the xDAI chain, is this a "normal" chain with hardforks and everything? Does this chain has got something like a `genesis.json` file or does someone have some informational source here to link to? Would be very interested to test the `Common` library against an xDAI configuration.

**Comment by cgewecke** [comment]
(Cross-linking to a recent related Hardhat issue: [hardhat 1177][1].) 

[1]: https://github.com/nomiclabs/hardhat/issues/1177

**Comment by holgerd77** [comment]
Will close in favor of #1323
