### ISSUE TITLE
Monorepo testing error

### ISSUE THREAD

**Issue by k06a** [ethereumjs/ethereumjs-monorepo#1311]
```
yarn && yarn test
```
```
> ethereumjs-util@7.0.10 test:browser
> karma start karma.conf.js


lerna ERR! npm run test stderr:
/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/node_modules/yargs/build/index.cjs:2804
            if (shim$1.Parser.looksLikeNumber(arg) &&
                              ^

TypeError: shim$1.Parser.looksLikeNumber is not a function
    at Object.Yargs.self._parsePositionalNumbers (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/node_modules/yargs/build/index.cjs:2804:31)
    at Object.Yargs.self._postProcess (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/node_modules/yargs/build/index.cjs:2787:25)
    at Object.runCommand (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/node_modules/yargs/build/index.cjs:439:19)
    at Object.parseArgs [as _parseArgs] (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/node_modules/yargs/build/index.cjs:2697:57)
    at Object.parse (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/node_modules/yargs/build/index.cjs:2278:29)
    at Object.exports.process (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/lib/cli.js:277:31)
    at Object.exports.run (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/lib/cli.js:282:30)
    at Object.<anonymous> (/Users/k06a/Projects/ethereumjs-monorepo/node_modules/karma/bin/karma:3:23)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)

lerna ERR! npm run test exited 1 in 'ethereumjs-util'
lerna WARN complete Waiting for 7 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by holgerd77** [comment]
Hi, sorry, this is not really well documented, but test runs for the whole monorepo are not really used and I wouldn't this expect to work TBH. Please use the local test run setups from the different packages instead if you want to run something specific.

Will try to better document, our whole monorepo setup and config docs generally need some update I guess!

**Comment by ryanio** [comment]
I just tried and `npm run test` actually does work for me from the root.

@k06a if you follow the README please try `npm i && npm run test` rather than yarn.

But as @holgerd77 mentioned our ci does more specific test runs from within each package, we don't use the top level test command since e.g. the `vm` has many different variations of state and blockchain tests.

For the most realistic test/ci setup you could fork this repo and create your own PRs on your own fork and then it should run the ci with the exact tests that would run on the main repo.

**Comment by k06a** [comment]
@ryanio using `npm` instead of `yarn` gives me the same result.

**Comment by ryanio** [comment]
Hm I haven't seen this error before, and our ci doesn't seem to run into it either, but it seems like it might be some dependency issue of `yargs` which is used in the client (https://github.com/snowpackjs/snowpack/discussions/1468#discussioncomment-281258)

I am wondering if since you did yarn first the node_modules folder perhaps got some conflicting versions.

We may also need to update our `yargs` version in client/package.json if it is outdated, haven't checked yet.

**Comment by holgerd77** [comment]
No follow up, will close.
