### ISSUE TITLE
Client Problems: Max Listener Memory Leak / Log Output Format / Snappy Errors / Invalid Trie Sync Stops

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#1539]
Various problems with our beloved client 🙂 making everything a bit production-unready atm, with some which might have been introduced along the latest merge work.

Not sure if it's wise to throw all this into one issue, but I also didn't want to blow things up too much, guess (most) things can be fixed along the sideline (I will actually directly start after posting here).

### 1. Max Listener Memory Leak

We still have a memory leak caused by too much event listeners added and not removed, this is from the server log:

![grafik](https://user-images.githubusercontent.com/931137/138416287-da46191c-d14c-4920-8600-ef328b90c48b.png)

Should be easily fixable though.

### 2. Log Output Format Error

The normal log output (so running from the console with `npm run client:start`) is now always adding a `39m` at the end of the colored labels from log lines, see e.g.:

![grafik](https://user-images.githubusercontent.com/931137/138416672-6edd4cd4-fe03-4688-bc53-6d89ca99e555.png)

This has close-to-for-sure been introduced along the log file work in the latest Merge PR and should be very close located to [these](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1530/commits/66d85b8254bf88066178168619b6ce2c74f794ef#diff-173fb668514dcea7ac8ade4e9aa5a8bc99e9f249ba779ecf9faa16bd4c424c15R36) changes. Had some look into that yesterday but couldn't completely locate and fix yet.

### 3. Snappy Errors

There are new snappy errors looking like this:

```shell
Oct 21 20:23:26 ip-10-0-101-22 nvm-exec[34634]: INFO [10-21|20:23:26] New sync target height number=13463136 hash=ca61a4a2...
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]: ERROR [10-21|20:23:31] Error: Invalid Snappy bitstream
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at Object.uncompress (/home/ubuntu/ethereumjs-monorepo/node_modules/snappyjs/index.js:88:13)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at Peer._handleBody (/home/ubuntu/ethereumjs-monorepo/packages/devp2p/src/rlpx/peer.ts:540:26)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at Peer._onSocketData (/home/ubuntu/ethereumjs-monorepo/packages/devp2p/src/rlpx/peer.ts:601:18)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at Socket.emit (events.js:400:28)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at Socket.emit (domain.js:475:12)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at addChunk (internal/streams/readable.js:293:12)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at readableAddChunk (internal/streams/readable.js:267:9)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at Socket.Readable.push (internal/streams/readable.js:206:10)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]:     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Oct 21 20:23:31 ip-10-0-101-22 nvm-exec[34634]: WARN [10-21|20:23:31] Server error: Error - Invalid Snappy bitstream
Oct 21 20:23:38 ip-10-0-101-22 nvm-exec[34634]: INFO [10-21|20:23:38] Imported blocks count=50 number=128919 hash=b74600d5... hardfork=chainstart peers=9
Oct 21 20:23:38 ip-10-0-101-22 nvm-exec[34634]: INFO [10-21|20:23:38] Executed blocks count=50 first=128918 hash=7bac555a... td=298457505472177195 hardfork=chainstart last=128968 hash=8c881ae2... with txs=11
```

These don't seem to break the control flow, but might have bad consequences under the hood (like a normally good peer getting disconnected or something) and therefore should be examined. Might be that my latest Snappy fix at #1484 didn't get it in the full turn (this was somewhat hacky in the first place).

Errors occur regularly so should be relatively easily be reproducable.

### 4. Invalid Trie Sync Stops

Last thing, likely the most severe/annoying one: sync (tested on `mainnet` on the server) breaks regularly (after a couple of 10.000 up to 100.000 blocks) with an `invalid receipt trie` or `invalid tx trie` or similar message, see e.g.:

![grafik](https://user-images.githubusercontent.com/931137/138418136-5a3f59de-de5b-4980-bc54-8093be2e7816.png)

This completely breaks the sync flow and sync is never picked up after that (bad 🙃). (Somewhat) good thing is is that sync *will* continue once the client gets restarted. So this rather hints at something like that we process a block in the wrong order or maybe handle a block or block common or the like in some occasions in a way which breaks the block setup and or structure.

Anyhow. To be analyzed.

Not totally easy because this can only be triggered relatively irregularly (it *does* happen though on every client start after maximally 30-60 minutes).

Guess the best attempt might be to really carefully craft in some meaningful debugging output additions and then just let it run on the sideline. Might give this a try during the day.

**Comment by holgerd77** [comment]
All somewhat addressed, client is syncing stable again, will close.
