### ISSUE TITLE
fromRpcSig, result is not defined 

### ISSUE THREAD

**Issue by danielnordh** [ethereumjs/ethereumjs-monorepo#1772]
I'm trying to get the signature parameters of a `.signTypedData` signature from eth-sig-util with `fromRpcSig` with the following test code:

```
const ethUtil = require("ethereumjs-util");
const signature = '0xdedda08da3fda75686c545b527c2a3eeb113f42e742aa0b2a75e664942d5d896381a8e439e3fb0aa126728d9e6c6cfe7aa02184d3e822937c84233baced04c6e1b';

const sigParams = ethUtil.fromRpcSig(signature);
console.log("Sigparams: " + sigparams);
```

But the result is an error:
```
console.log("Sigparams: " + sigparams);
                            ^
ReferenceError: sigparams is not defined
    at Object.<anonymous> (/Users/daniel/Code/nodetest/app.js:64:29)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

I have also tried passing the buffer of the signature with:
```
const sigBuffer = ethUtil.toBuffer(signature);
const sigParams = ethUtil.fromRpcSig(sigBuffer);
```
And the sigBuffer value is created, but the sigParams is still not.

I first thought it may have something to do with accessing the function somehow, but I installed the normal way with 
`npm install ethereumjs-util`, and the fact that the sigBuffer value is created as expected makes that less likely.

**Comment by ryanio** [comment]
Your const is sigParams but you're console logging sigparams (all lowercase)
