### ISSUE TITLE
Account Abstraction support (EIP-3074): analyze Hardhat test failures

### ISSUE THREAD

**Issue by wschwab** [ethereumjs/ethereumjs-monorepo#2332]
Hello!

I was wondering if it's possible to ask for support for [EIP-3074](https://eips.ethereum.org/EIPS/eip-3074) (Account Abstraction) in the EthereumJS EVM. This would be very helpful for testing, seeing as Hardhat uses EthereumJS for their EVM, and a big part of 3074 is creating invoker contracts that leverage the opcodes introduced by the EIP.

Is there a way the 3074 opcodes could be added as experimental opcodes?

I'm happy to talk more about why I think this is a worthwhile feature, who's looking for this, etc.

Thanks for reading!

**Comment by wschwab** [comment]
That's great to hear! I'm 404-ing on that link, though.

**Comment by acolytec3** [comment]
Sorry, we just did some directory renaming. Try [this](https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/vm/test/api/EIPs/eip-3074-authcall.spec.ts)

**Comment by wschwab** [comment]
Sorry I hadn't gotten back to this, we're good on this front, closing issue.

**Comment by wschwab** [comment]
ok, truth is, we're having a bit of trouble figuring out how to get this initialized in a Hardhat environment. Currently we're using this snippet inside Hardhat config:
```javascript
const { Common } = require("@nomicfoundation/ethereumjs-common");
const originalCustom = Common.custom;
Common.custom = (params, opts) => {
  return originalCustom.call(Common, params, {
    ...opts,
    eips: [...(opts.eips ?? []), 3074],
  });
};
```
But then calling `auth` in tests fails from out-of-gas. Is there something else we need to be doing?

**Comment by holgerd77** [comment]
Hmm, I wonder if you should rather start opening this on the Hardhat side. 🤔

I have not so deep insights on how Hardhat is using the VM and where things are injected/initialized in what way. Feel very free to tag me there if you do.

I just checked by installing the latest Hardhat, so the `@nomicfoundation/ethereumjs-common` fork seems to have 3074 included, also the VM/EVM combination used.

What might help here if you paste some more detailed console output while running your `auth` tests.

**Comment by ZeroEkkusu** [comment]
Hi, @holgerd77,

Correct, 3074 seems to be included, because transactions would otherwise fail with the invalid opcode error.

With the snippet added, this is what happens when the execution gets to `AUTH` opcode:

In tests that expect a failure later (e.g. `AUTH` should return an address that would not satisfy a `require` statement):

```
AssertionError: Expected transaction to be reverted with reason 'Invalid signature', but it reverted without a reason
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at runNextTicks (node:internal/process/task_queues:65:3)
  at listOnTimeout (node:internal/timers:528:9)
  at processTimers (node:internal/timers:502:7)
  at async Context.<anonymous> (test/AccountAbstractionInvoker.ts:145:7)
```

In tests that expect the transaction to succeed:

```
TransactionExecutionError: Transaction ran out of gas
  at HardhatNode._manageErrors (/Users/.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1961:14)
  at HardhatNode._gatherTraces (/Users/.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1677:30)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at runNextTicks (node:internal/process/task_queues:65:3)
  at listOnTimeout (node:internal/timers:528:9)
  at processTimers (node:internal/timers:502:7)
  at async HardhatNode._mineBlockWithPendingTxs (/Users/.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1802:23)
  at async HardhatNode.mineBlock (/Users/.../node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:491:16)
  at async EthModule._sendTransactionAndReturnHash (/Users/.../node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
  at async HardhatNetworkProvider.request (/Users/.../node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
```

The execution stops at `AUTH` opcode in both cases.

Please, let me know if you have ideas. Thank you.

**Comment by jochem-brouwer** [comment]
Hi @wschwab, could you show me which test this is exactly? We cannot help you if we do not see how/what you are testing :smile:

**Comment by ZeroEkkusu** [comment]
Hi, @jochem-brouwer,

Here are the tests for the outputs above:

- A [test](https://github.com/0xPolygon/account-abstraction-invoker/blob/05eae77034ba8e11cf66de5c926254cff0a7f3f7/test/AccountAbstractionInvoker.ts#L133-L148) that expect a failure later
- A [test](https://github.com/0xPolygon/account-abstraction-invoker/blob/05eae77034ba8e11cf66de5c926254cff0a7f3f7/test/AccountAbstractionInvoker.ts#L247-L273) expects the transaction to succeed

The tests work on a custom network, but not on Hardhat's local one.

**Comment by holgerd77** [comment]
Will close due to inactivity and likely changes in all context systems (EthereumJS, Hardhat).

Feel free to reopen if this is still a thing!
