### ISSUE TITLE
Expected Uint8Array Error occured at each new epoch

### ISSUE THREAD

**Issue by monstermax** [ethereumjs/ethereumjs-monorepo#2432]
Hi all,

Using a homemade client built on EthereumJS packages, at each new epoch (blocks 60000,90000,120000,... but not the 30000th ?!) i got an error :
 ```
        throw new TypeError('Expected Uint8Array');
              ^

TypeError: Expected Uint8Array
    at Object.bytes (/home/karma/dev/perso/ethnode/node_modules/@noble/hashes/_assert.js:16:15)
    at /home/karma/dev/perso/ethnode/node_modules/ethereum-cryptography/utils.js:49:27
    at getSeed (/home/karma/dev/perso/ethnode/node_modules/@ethereumjs/ethash/dist/util.js:54:51)
    at Ethash.loadEpoc (/home/karma/dev/perso/ethnode/node_modules/@ethereumjs/ethash/dist/index.js:236:44)
    at async Ethash._verifyPOW (/home/karma/dev/perso/ethnode/node_modules/@ethereumjs/ethash/dist/index.js:267:9)
    at async Ethash.verifyPOW (/home/karma/dev/perso/ethnode/node_modules/@ethereumjs/ethash/dist/index.js:277:23)
    at async EthashConsensus.validateConsensus (/home/karma/dev/perso/ethnode/node_modules/@ethereumjs/blockchain/dist/consensus/ethash.js:17:23)
```

I could apply an ugly patch but I don't know why and how this bug occured.
https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/ethash/src/index.ts#L294
```js
if (data) {
    if ('data' in data.seed) data.seed = Buffer.from(data.seed.data, 'hex'); // PATCH
    return [data.seed, epoc];
}
```
The `data.seed` should be a `Buffer` but it is a `JSON` encoded `Buffer` which comes in the value.

If someone can tell me why I get this problem it would help me a lot.

Notice: using the official EthereumJS client, I do not have the problem.

**Comment by acolytec3** [comment]
Sorry for the slow follow up here.  Can you provide a link to where you are using this code so we can research further?  I'm wondering if your database configuration is the issue.

**Comment by acolytec3** [comment]
If this is still an issue, please let us know. In our next round of breaking releases, we're switching from `buffer` to `uint8array` so notionally that may help your issue. Closing for now but please reopen if needed
