### ISSUE TITLE
Hive tests failing

### ISSUE THREAD

**Issue by jochem-brouwer** [ethereumjs/ethereumjs-monorepo#2498]
Currently, we have failing hive tests (on hive `master` branch). 

In the [hive](https://github.com/ethereum/hive) repository, in order to run local code, change `clients/ethereumjs/Dockerfile` to:

```
FROM node:16-alpine as build
RUN apk update && apk add --no-cache bash git jq curl python3 gcc make g++ && rm -rf /var/cache/apk/*
ADD ethereumjs-monorepo /ethereumjs-monorepo
RUN cd ethereumjs-monorepo && npm i

RUN cd ethereumjs-monorepo/packages/client

ADD ethereumjs.sh /ethereumjs.sh
ADD mapper.jq /mapper.jq
ADD jwtsecret /jwtsecret
RUN chmod +x /ethereumjs.sh

# Inject the enode id retriever script
RUN mkdir /hive-bin
ADD enode.sh /hive-bin/enode.sh
RUN chmod +x /hive-bin/enode.sh

ADD genesis.json /genesis.json

# Export the usual networking ports to allow outside access to the node
EXPOSE 8545 8546 8551 8547 30303 30303/udp

# NodeJS applications have a default memory limit of 2.5GB.
# This limit is bit tight, it is recommended to raise the limit
# since memory may spike during certain network conditions.
ENV NODE_OPTIONS=--max_old_space_size=6144

ENTRYPOINT ["/ethereumjs.sh"]
```

You will need to copy/clone `ethereumjs-monorepo` into the `clients/ethereumjs` directory of hive. Note: tests are still somewhat slow since each time hive is started it will copy the entire directory into the docker container.

**Comment by jochem-brouwer** [comment]
`engine-withdrawals` currently (after #2502)

```
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs/hive$ sudo go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-withdrawals"
INFO[01-24|17:39:31] building image                           image=hive/hiveproxy nocache=false pull=false
INFO[01-24|17:39:31] building 1 clients... 
INFO[01-24|17:39:31] building image                           image=hive/clients/ethereumjs:latest dir=clients/ethereumjs nocache=false pull=false
WARN[01-24|17:39:43] can't read version info of ethereumjs    image=hive/clients/ethereumjs:latest err="API error (404): Could not find the file /version.txt in container 2487ae18b4c2997b4d2ef16fc2aef916ae095dc97211a4097f11e5c4ef01a88d"
INFO[01-24|17:39:43] building 1 simulators... 
INFO[01-24|17:39:43] building image                           image=hive/simulators/ethereum/engine:latest dir=simulators/ethereum/engine nocache=false pull=false
INFO[01-24|17:39:43] running simulation: ethereum/engine 
INFO[01-24|17:39:44] hiveproxy started                        container=16bfd3f76fac addr=172.17.0.2:8081
INFO[01-24|17:39:44] API: suite started                       suite=0 name=engine-withdrawals
INFO[01-24|17:39:44] API: test started                        suite=0 test=1 name="Withdrawals Fork On Genesis (ethereumjs)"
EROR[01-24|17:39:48] API: could not start client              client=ethereumjs container=4899bca4 error="terminated unexpectedly"
INFO[01-24|17:39:48] API: test ended                          suite=0 test=1 pass=false
INFO[01-24|17:39:48] API: test started                        suite=0 test=2 name="Withdrawals Fork on Block 1 (ethereumjs)"
INFO[01-24|17:39:52] API: client ethereumjs started           suite=0 test=2 container=15ec9f7a
INFO[01-24|17:39:56] API: test ended                          suite=0 test=2 pass=true
INFO[01-24|17:39:56] API: test started                        suite=0 test=3 name="Withdrawals Fork on Block 2 (ethereumjs)"
INFO[01-24|17:40:01] API: client ethereumjs started           suite=0 test=3 container=310af157
INFO[01-24|17:40:06] API: test ended                          suite=0 test=3 pass=true
INFO[01-24|17:40:06] API: test started                        suite=0 test=4 name="Withdrawals Fork on Block 3 (ethereumjs)"
INFO[01-24|17:40:10] API: client ethereumjs started           suite=0 test=4 container=a4e61a86
INFO[01-24|17:40:16] API: test ended                          suite=0 test=4 pass=true
INFO[01-24|17:40:16] API: test started                        suite=0 test=5 name="Withdraw to a single account (ethereumjs)"
INFO[01-24|17:40:20] API: client ethereumjs started           suite=0 test=5 container=1791f59f
INFO[01-24|17:40:24] API: test ended                          suite=0 test=5 pass=true
INFO[01-24|17:40:24] API: test started                        suite=0 test=6 name="Withdraw to two accounts (ethereumjs)"
INFO[01-24|17:40:28] API: client ethereumjs started           suite=0 test=6 container=c497c83f
INFO[01-24|17:40:32] API: test ended                          suite=0 test=6 pass=true
INFO[01-24|17:40:32] API: test started                        suite=0 test=7 name="Withdraw many accounts (ethereumjs)"
INFO[01-24|17:40:37] API: client ethereumjs started           suite=0 test=7 container=d940c94d
INFO[01-24|17:44:08] API: test ended                          suite=0 test=7 pass=true
INFO[01-24|17:44:08] API: test started                        suite=0 test=8 name="Withdraw zero amount (ethereumjs)"
INFO[01-24|17:44:12] API: client ethereumjs started           suite=0 test=8 container=0cc94f56
INFO[01-24|17:44:16] API: test ended                          suite=0 test=8 pass=true
INFO[01-24|17:44:16] API: test started                        suite=0 test=9 name="Empty Withdrawals (ethereumjs)"
INFO[01-24|17:44:20] API: client ethereumjs started           suite=0 test=9 container=7c6b0068
INFO[01-24|17:44:24] API: test ended                          suite=0 test=9 pass=true
INFO[01-24|17:44:24] API: test started                        suite=0 test=10 name="Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account - No Transactions (ethereumjs)"
INFO[01-24|17:44:28] API: client ethereumjs started           suite=0 test=10 container=8317268c
INFO[01-24|17:44:32] API: container IP requested              network=bridge container=8317268c ip=172.17.0.4
INFO[01-24|17:44:36] API: client ethereumjs started           suite=0 test=10 container=eb511176
INFO[01-24|17:44:47] API: test ended                          suite=0 test=10 pass=true
INFO[01-24|17:44:47] API: test started                        suite=0 test=11 name="Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account (ethereumjs)"
INFO[01-24|17:44:51] API: client ethereumjs started           suite=0 test=11 container=ecfb1ae6
INFO[01-24|17:44:55] API: container IP requested              network=bridge container=ecfb1ae6 ip=172.17.0.4
INFO[01-24|17:44:59] API: client ethereumjs started           suite=0 test=11 container=2d66b3b7
INFO[01-24|17:45:10] API: test ended                          suite=0 test=11 pass=true
INFO[01-24|17:45:10] API: test started                        suite=0 test=12 name="Sync after 2 blocks - Withdrawals on Genesis - Single Withdrawal Account (ethereumjs)"
EROR[01-24|17:45:15] API: could not start client              client=ethereumjs container=d7b96e03 error="terminated unexpectedly"
INFO[01-24|17:45:15] API: test ended                          suite=0 test=12 pass=false
INFO[01-24|17:45:15] API: test started                        suite=0 test=13 name="Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts - No Transactions (ethereumjs)"
INFO[01-24|17:45:19] API: client ethereumjs started           suite=0 test=13 container=4e6745fa
INFO[01-24|17:45:23] API: container IP requested              network=bridge container=4e6745fa ip=172.17.0.4
INFO[01-24|17:45:28] API: client ethereumjs started           suite=0 test=13 container=b07ce0f1
INFO[01-24|17:45:38] API: test ended                          suite=0 test=13 pass=false
INFO[01-24|17:45:38] API: test started                        suite=0 test=14 name="Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts (ethereumjs)"
INFO[01-24|17:45:42] API: client ethereumjs started           suite=0 test=14 container=ca659a9d
INFO[01-24|17:45:47] API: container IP requested              network=bridge container=ca659a9d ip=172.17.0.4
INFO[01-24|17:45:51] API: client ethereumjs started           suite=0 test=14 container=9cc0a77c
INFO[01-24|17:46:01] API: test ended                          suite=0 test=14 pass=false
```

**Comment by holgerd77** [comment]
Also pasting here for reference, start command is (as posted by Jochem in the chat):

```shell
go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-withdrawals/Withdrawals Fork on Block 1"
```

**Comment by holgerd77** [comment]
Just tested this, I guess this is generally working, pretty cool! 🤩

Totally nothing to be quickly solved, but at the moment I get on the test runs:

```shell
INFO[01-24|20:22:05] building image                           image=hive/hiveproxy nocache=false pull=false
INFO[01-24|20:25:33] building 1 clients...
INFO[01-24|20:25:33] building image                           image=hive/clients/ethereumjs:latest dir=clients/ethereumjs nocache=false pull=false
WARN[01-24|20:32:02] can't read version info of ethereumjs    image=hive/clients/ethereumjs:latest err="API error (404): Could not find the file /version.txt in container 04838b8f0220ed7cad234a6e904d096eecdf40254b268aaad1805f6fb3a1af25"
INFO[01-24|20:32:02] building 1 simulators...
INFO[01-24|20:32:02] building image                           image=hive/simulators/ethereum/engine:latest dir=simulators/ethereum/engine nocache=false pull=false
INFO[01-24|20:35:56] creating output directory                folder=workspace/logs
INFO[01-24|20:35:56] running simulation: ethereum/engine
INFO[01-24|20:35:56] hiveproxy started                        container=289e5392607f addr=172.17.0.2:8081
INFO[01-24|20:35:57] API: suite started                       suite=0 name=engine-withdrawals
INFO[01-24|20:35:57] API: test started                        suite=0 test=1 name="Withdrawals Fork on Block 1 (ethereumjs)"
EROR[01-24|20:36:02] API: could not start client              client=ethereumjs container=0021834f error="terminated unexpectedly"
INFO[01-24|20:36:02] API: test ended                          suite=0 test=1 pass=false
INFO[01-24|20:36:02] API: test started                        suite=0 test=2 name="Withdrawals Fork on Block 1 - 1 Block Re-Org (ethereumjs)"
EROR[01-24|20:36:05] API: could not start client              client=ethereumjs container=759d82be error="terminated unexpectedly"
INFO[01-24|20:36:05] API: test ended                          suite=0 test=2 pass=false
INFO[01-24|20:36:05] API: test started                        suite=0 test=3 name="Withdrawals Fork on Block 1 - 8 Block Re-Org NewPayload (ethereumjs)"
EROR[01-24|20:36:09] API: could not start client              client=ethereumjs container=35e7be50 error="terminated unexpectedly"
INFO[01-24|20:36:09] API: test ended                          suite=0 test=3 pass=false
INFO[01-24|20:36:09] API: test started                        suite=0 test=4 name="Withdrawals Fork on Block 1 - 8 Block Re-Org, Sync (ethereumjs)"
EROR[01-24|20:36:12] API: could not start client              client=ethereumjs container=385c97d5 error="terminated unexpectedly"
INFO[01-24|20:36:12] API: test ended                          suite=0 test=4 pass=false
INFO[01-24|20:36:12] API: suite ended                         suite=0
INFO[01-24|20:36:12] simulation ethereum/engine finished      suites=1 tests=4 failed=4
```

just dropping here, maybe we can exchange tomorrow on that or so or you see a quick solution or remember something which might not be in the docs or so.

Again: totally not urgent, was just curious.

**Comment by holgerd77** [comment]
(side note: we should open a section in our client developer docs on Hive and also integrate the documentation from here on the local runs)

**Comment by jochem-brouwer** [comment]
I do not recall this exact version. Are you running from hive master? And are you running the dockerfile I provided here? If the latter is yes make sure you have an actual clone of the monorepo. No symlinks.

Otherwise we discuss tomorrow!

**Comment by jochem-brouwer** [comment]
```
jochem@jochem-OMEN-Laptop-15-ek1xxx:~/Documents/ejs/hive$ sudo go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-withdrawals"
INFO[01-26|09:56:36] building image                           image=hive/hiveproxy nocache=false pull=false
INFO[01-26|09:56:36] building 1 clients... 
INFO[01-26|09:56:36] building image                           image=hive/clients/ethereumjs:latest dir=clients/ethereumjs nocache=false pull=false
INFO[01-26|09:56:48] building 1 simulators... 
INFO[01-26|09:56:48] building image                           image=hive/simulators/ethereum/engine:latest dir=simulators/ethereum/engine nocache=false pull=false
INFO[01-26|09:56:48] running simulation: ethereum/engine 
INFO[01-26|09:56:48] hiveproxy started                        container=16d6b4cb2a23 addr=172.17.0.2:8081
INFO[01-26|09:56:49] API: suite started                       suite=0 name=engine-withdrawals
INFO[01-26|09:56:49] API: test started                        suite=0 test=1 name="Withdrawals Fork On Genesis (ethereumjs)"
INFO[01-26|09:56:53] API: client ethereumjs started           suite=0 test=1 container=8ead0e99
INFO[01-26|09:56:59] API: test ended                          suite=0 test=1 pass=true
INFO[01-26|09:56:59] API: test started                        suite=0 test=2 name="Withdrawals Fork on Block 1 (ethereumjs)"
INFO[01-26|09:57:03] API: client ethereumjs started           suite=0 test=2 container=b2f773cd
INFO[01-26|09:57:07] API: test ended                          suite=0 test=2 pass=true
INFO[01-26|09:57:07] API: test started                        suite=0 test=3 name="Withdrawals Fork on Block 2 (ethereumjs)"
INFO[01-26|09:57:11] API: client ethereumjs started           suite=0 test=3 container=2d15d673
INFO[01-26|09:57:16] API: test ended                          suite=0 test=3 pass=true
INFO[01-26|09:57:16] API: test started                        suite=0 test=4 name="Withdrawals Fork on Block 3 (ethereumjs)"
INFO[01-26|09:57:20] API: client ethereumjs started           suite=0 test=4 container=ae4fcc39
INFO[01-26|09:57:26] API: test ended                          suite=0 test=4 pass=true
INFO[01-26|09:57:26] API: test started                        suite=0 test=5 name="Withdraw to a single account (ethereumjs)"
INFO[01-26|09:57:30] API: client ethereumjs started           suite=0 test=5 container=3263a5ce
INFO[01-26|09:57:34] API: test ended                          suite=0 test=5 pass=true
INFO[01-26|09:57:34] API: test started                        suite=0 test=6 name="Withdraw to two accounts (ethereumjs)"
INFO[01-26|09:57:38] API: client ethereumjs started           suite=0 test=6 container=57e2473c
INFO[01-26|09:57:42] API: test ended                          suite=0 test=6 pass=true
INFO[01-26|09:57:42] API: test started                        suite=0 test=7 name="Withdraw many accounts (ethereumjs)"
INFO[01-26|09:57:47] API: client ethereumjs started           suite=0 test=7 container=7538730f
INFO[01-26|10:01:10] API: test ended                          suite=0 test=7 pass=true
INFO[01-26|10:01:10] API: test started                        suite=0 test=8 name="Withdraw zero amount (ethereumjs)"
INFO[01-26|10:01:14] API: client ethereumjs started           suite=0 test=8 container=347ce175
INFO[01-26|10:01:18] API: test ended                          suite=0 test=8 pass=true
INFO[01-26|10:01:18] API: test started                        suite=0 test=9 name="Empty Withdrawals (ethereumjs)"
INFO[01-26|10:01:22] API: client ethereumjs started           suite=0 test=9 container=fe6fe031
INFO[01-26|10:01:26] API: test ended                          suite=0 test=9 pass=true
INFO[01-26|10:01:26] API: test started                        suite=0 test=10 name="Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account - No Transactions (ethereumjs)"
INFO[01-26|10:01:30] API: client ethereumjs started           suite=0 test=10 container=b59acaeb
INFO[01-26|10:01:34] API: container IP requested              network=bridge container=b59acaeb ip=172.17.0.4
INFO[01-26|10:01:38] API: client ethereumjs started           suite=0 test=10 container=273fb95c
INFO[01-26|10:01:49] API: test ended                          suite=0 test=10 pass=true
INFO[01-26|10:01:49] API: test started                        suite=0 test=11 name="Sync after 2 blocks - Withdrawals on Block 1 - Single Withdrawal Account (ethereumjs)"
INFO[01-26|10:01:53] API: client ethereumjs started           suite=0 test=11 container=b4831d37
INFO[01-26|10:01:57] API: container IP requested              network=bridge container=b4831d37 ip=172.17.0.4
INFO[01-26|10:02:01] API: client ethereumjs started           suite=0 test=11 container=f96460d8
INFO[01-26|10:02:12] API: test ended                          suite=0 test=11 pass=true
INFO[01-26|10:02:12] API: test started                        suite=0 test=12 name="Sync after 2 blocks - Withdrawals on Genesis - Single Withdrawal Account (ethereumjs)"
INFO[01-26|10:02:16] API: client ethereumjs started           suite=0 test=12 container=6e905eb8
INFO[01-26|10:02:20] API: container IP requested              network=bridge container=6e905eb8 ip=172.17.0.4
INFO[01-26|10:02:24] API: client ethereumjs started           suite=0 test=12 container=61e85b10
INFO[01-26|10:02:35] API: test ended                          suite=0 test=12 pass=true
INFO[01-26|10:02:35] API: test started                        suite=0 test=13 name="Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts - No Transactions (ethereumjs)"
INFO[01-26|10:02:39] API: client ethereumjs started           suite=0 test=13 container=cfa230ec
INFO[01-26|10:02:44] API: container IP requested              network=bridge container=cfa230ec ip=172.17.0.4
INFO[01-26|10:02:48] API: client ethereumjs started           suite=0 test=13 container=ec742481
INFO[01-26|10:02:58] API: test ended                          suite=0 test=13 pass=false
INFO[01-26|10:02:58] API: test started                        suite=0 test=14 name="Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts (ethereumjs)"
INFO[01-26|10:03:02] API: client ethereumjs started           suite=0 test=14 container=4d27a0e1
INFO[01-26|10:03:07] API: container IP requested              network=bridge container=4d27a0e1 ip=172.17.0.4
INFO[01-26|10:03:11] API: client ethereumjs started           suite=0 test=14 container=5189e253
INFO[01-26|10:03:21] API: test ended                          suite=0 test=14 pass=false
INFO[01-26|10:03:21] API: test started                        suite=0 test=15 name="Sync after 128 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts (ethereumjs)"
INFO[01-26|10:03:26] API: client ethereumjs started           suite=0 test=15 container=20adb32e
INFO[01-26|10:06:11] API: container IP requested              network=bridge container=20adb32e ip=172.17.0.4
INFO[01-26|10:06:16] API: client ethereumjs started           suite=0 test=15 container=52bf685e
INFO[01-26|10:08:27] API: test ended                          suite=0 test=15 pass=false
INFO[01-26|10:08:27] API: test started                        suite=0 test=16 name="Withdrawals Fork on Block 1 - 1 Block Re-Org (ethereumjs)"
INFO[01-26|10:08:31] API: client ethereumjs started           suite=0 test=16 container=c6b34bf1
INFO[01-26|10:08:33] API: container IP requested              network=bridge container=c6b34bf1 ip=172.17.0.4
INFO[01-26|10:08:37] API: client ethereumjs started           suite=0 test=16 container=e4b24a31
INFO[01-26|10:09:42] API: test ended                          suite=0 test=16 pass=false
INFO[01-26|10:09:42] API: test started                        suite=0 test=17 name="Withdrawals Fork on Block 1 - 8 Block Re-Org NewPayload (ethereumjs)"
INFO[01-26|10:09:46] API: client ethereumjs started           suite=0 test=17 container=26108404
INFO[01-26|10:09:48] API: container IP requested              network=bridge container=26108404 ip=172.17.0.4
INFO[01-26|10:09:52] API: client ethereumjs started           suite=0 test=17 container=716d3501
INFO[01-26|10:10:57] API: test ended                          suite=0 test=17 pass=false
INFO[01-26|10:10:57] API: test started                        suite=0 test=18 name="Withdrawals Fork on Block 1 - 8 Block Re-Org, Sync (ethereumjs)"
INFO[01-26|10:11:01] API: client ethereumjs started           suite=0 test=18 container=465fe6da
INFO[01-26|10:11:03] API: container IP requested              network=bridge container=465fe6da ip=172.17.0.4
INFO[01-26|10:11:07] API: client ethereumjs started           suite=0 test=18 container=040ea1b0
INFO[01-26|10:12:12] API: test ended                          suite=0 test=18 pass=false
INFO[01-26|10:12:12] API: test started                        suite=0 test=19 name="Withdrawals Fork on Block 8 - 10 Block Re-Org NewPayload (ethereumjs)"
INFO[01-26|10:12:16] API: client ethereumjs started           suite=0 test=19 container=e2b72c27
INFO[01-26|10:12:18] API: container IP requested              network=bridge container=e2b72c27 ip=172.17.0.4
INFO[01-26|10:12:22] API: client ethereumjs started           suite=0 test=19 container=3a6bdce2
INFO[01-26|10:13:27] API: test ended                          suite=0 test=19 pass=false
INFO[01-26|10:13:27] API: test started                        suite=0 test=20 name="Withdrawals Fork on Block 8 - 10 Block Re-Org Sync (ethereumjs)"
INFO[01-26|10:13:31] API: client ethereumjs started           suite=0 test=20 container=dcd58c43
INFO[01-26|10:13:33] API: container IP requested              network=bridge container=dcd58c43 ip=172.17.0.4
INFO[01-26|10:13:37] API: client ethereumjs started           suite=0 test=20 container=93070f21
INFO[01-26|10:14:42] API: test ended                          suite=0 test=20 pass=false
INFO[01-26|10:14:42] API: test started                        suite=0 test=21 name="Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org (ethereumjs)"
INFO[01-26|10:14:46] API: client ethereumjs started           suite=0 test=21 container=c8ebec4d
INFO[01-26|10:14:48] API: container IP requested              network=bridge container=c8ebec4d ip=172.17.0.4
INFO[01-26|10:14:52] API: client ethereumjs started           suite=0 test=21 container=31a5da3b
INFO[01-26|10:15:57] API: test ended                          suite=0 test=21 pass=false
INFO[01-26|10:15:57] API: test started                        suite=0 test=22 name="Withdrawals Fork on Canonical Block 8 / Side Block 7 - 10 Block Re-Org Sync (ethereumjs)"
INFO[01-26|10:16:02] API: client ethereumjs started           suite=0 test=22 container=30d64bbb
INFO[01-26|10:16:03] API: container IP requested              network=bridge container=30d64bbb ip=172.17.0.4
INFO[01-26|10:16:07] API: client ethereumjs started           suite=0 test=22 container=fb859ce2
INFO[01-26|10:17:12] API: test ended                          suite=0 test=22 pass=false
INFO[01-26|10:17:12] API: test started                        suite=0 test=23 name="Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org (ethereumjs)"
INFO[01-26|10:17:17] API: client ethereumjs started           suite=0 test=23 container=f7ad7144
INFO[01-26|10:17:18] API: container IP requested              network=bridge container=f7ad7144 ip=172.17.0.4
INFO[01-26|10:17:22] API: client ethereumjs started           suite=0 test=23 container=230ad9be
INFO[01-26|10:18:27] API: test ended                          suite=0 test=23 pass=false
INFO[01-26|10:18:27] API: test started                        suite=0 test=24 name="Withdrawals Fork on Canonical Block 8 / Side Block 9 - 10 Block Re-Org Sync (ethereumjs)"
INFO[01-26|10:18:32] API: client ethereumjs started           suite=0 test=24 container=d72f07d6
INFO[01-26|10:18:33] API: container IP requested              network=bridge container=d72f07d6 ip=172.17.0.4
INFO[01-26|10:18:37] API: client ethereumjs started           suite=0 test=24 container=2ca9a0a7
INFO[01-26|10:19:43] API: test ended                          suite=0 test=24 pass=false
INFO[01-26|10:19:43] API: test started                        suite=0 test=25 name="Max Initcode Size (ethereumjs)"
INFO[01-26|10:19:47] API: client ethereumjs started           suite=0 test=25 container=cded8f11
INFO[01-26|10:19:51] API: test ended                          suite=0 test=25 pass=false
INFO[01-26|10:19:52] API: suite ended                         suite=0
INFO[01-26|10:19:52] simulation ethereum/engine finished      suites=1 tests=25 failed=13
```

EthereumJS branch: `fix-hive-tests`

Hive branch: `fix-capella-genesis-engine`

**Comment by holgerd77** [comment]
@jochem-brouwer this looks already pretty good! 🤩 🙂

**Comment by jochem-brouwer** [comment]
Some quick notes regarding hive tests and how to debug them if they are failing:

In the hive repo, if test(s) are ran, a `logs` folder will appear in `workspaces`. This contains the logs of the docker output of each of the clients which are spawned, plus the logs of the simulator runner itself.

In case that the client throws with errors (for instance internal error) over RPC, then the test will fail (regardless of if the final state of the chain is correct). 

The workspace logs are not cleared if a new test is started, so in order to find the relevant logs it makes sense to first empty the logs folder.

To run a specific log with rich output, use for instance:

`go run ./hive.go --client ethereumjs --sim ethereum/engine --sim.limit "engine-withdrawals/Sync after 2 blocks - Withdrawals on Block 2 - Multiple Withdrawal Accounts - No Transactions" --docker.output --sim.loglevel 5`

**Comment by g11tech** [comment]
more tests are to be fixed, reopening

**Comment by fjl** [comment]
We can now also run the `pyspec` (https://github.com/ethereum/execution-specs) tests on hive. They run on https://hivetests.ethdevops.io. Unfortunately, ethereumjs fails them all with this error:

```
Supplied genesis state:
{
  "config": {
    "ethash": {},
    "chainId": 1,
    "homesteadBlock": 0,
    "daoForkSupport": true,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "berlinBlock": 0,
    "yolov2Block": 0,
    "yolov3Block": 0,
    "londonBlock": 0,
    "terminalTotalDifficulty": 0,
    "shanghaiTime": 0
  },
  "nonce": "0x0",
  "timestamp": "0x0",
  "extraData": "0x00",
  "gasLimit": "0x16345785d8a0000",
  "difficulty": "0x0",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {},
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "baseFeePerGas": "0x7"
}
Loading initial blockchain...
Warning: chain.rlp not found.
Running ethereumjs with flags --gethGenesis ./genesis.json --rpc --rpcEngine --saveReceipts --rpcEnginePort 8551 --ws --logLevel debug --rpcDebug --transports rlpx --isSingleNode --jwt-secret ./jwtsecret --bootnodes=
[03-22|19:08:16] INFO Reading custom genesis state accounts=0 
[03-22|19:08:16] INFO Data directory: /root/Library/Ethereum/ethereumjs
Error: The provided number is greater than MAX_SAFE_INTEGER (please use an alternative input type)
    at toType (/ethereumjs-monorepo/packages/util/dist/types.js:27:15)
    at new BlockHeader (/ethereumjs-monorepo/packages/block/dist/header.js:64:44)
    at Function.fromHeaderData (/ethereumjs-monorepo/packages/block/dist/header.js:158:16)
    at Function.fromBlockData (/ethereumjs-monorepo/packages/block/dist/block.js:90:45)
    at Blockchain.createGenesisBlock (/ethereumjs-monorepo/packages/blockchain/dist/blockchain.js:1145:30)
    at Blockchain._init (/ethereumjs-monorepo/packages/blockchain/dist/blockchain.js:157:33)
    at async Function.create (/ethereumjs-monorepo/packages/blockchain/dist/blockchain.js:90:9)
    at async startClient (/ethereumjs-monorepo/packages/client/dist/bin/cli.js:369:22)
    at async run (/ethereumjs-monorepo/packages/client/dist/bin/cli.js:686:20)
[03-22|19:08:16] ERROR The provided number is greater than MAX_SAFE_INTEGER (please use an alternative input type)
```

**Comment by jochem-brouwer** [comment]
@fjl Thanks a lot for reporting, will take a look!

**Comment by acolytec3** [comment]
Should we keep this open? We aren't passing all the hive tests yet but we've made a lot of progress since this was opened and would be worth either opening specific issues for test suites that are failing or just pushing to did them all as a team at some point.
