### ISSUE TITLE
@Chainsafe/ssz Uncaught TypeError: Cannot convert a BigInt value to a number

### ISSUE THREAD

**Issue by sebastiendan** [ethereumjs/ethereumjs-monorepo#2595]
npm package version: `5.0.4`

When using the package in a react web app, I face this error on page load. This seems internal to `@ethereumjs/trie` and notably its use of `@chainsafe/ssz`.

I was previously using the `merkle-patricia-tree` npm package which seems to be an older version of `@ethereumjs/trie`?

```
Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at ./node_modules/@chainsafe/ssz/lib/type/uint.js (uint.ts:10:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@chainsafe/ssz/lib/index.js (index.ts:12:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/util/dist/ssz.js (ssz.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/util/dist/index.js (index.ts:39:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (branch.ts:2:1)
    at ./node_modules/@ethereumjs/trie/dist/trie/node/branch.js (branch.ts:6:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/trie/node/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/trie/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object.<anonymous> (range.ts:1:1)
    at ./node_modules/@ethereumjs/trie/dist/proof/range.js (range.ts:410:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/proof/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/@ethereumjs/trie/dist/index.js (index.ts:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (Step1.tsx:388:1)
    at ./src/components/steps/Step2.tsx (Step2.tsx:268:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (MetaMask.tsx:58:1)
    at ./src/components/MultiStepForm.tsx (MultiStepForm.tsx:132:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (main.chunk.js:19:83)
    at ./src/App.tsx (App.tsx:53:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (useRegisteredTokens.ts:10:1)
    at ./src/index.tsx (index.tsx:21:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at 1 (index.ts:41:1)
```

**Comment by acolytec3** [comment]
I think this is more likely a React issue than anything specific to our library or even SSZ since I traced down the exact line in the Chainsafe code that causes the error [here](https://github.com/ChainSafe/ssz/blob/dbae75afb0766e70966e77d68ba4880bd1001902/packages/ssz/src/type/uint.ts#L10) and there's nothing unusual there.  Can you point me to an example repo with your react setup?  It looks like react is transpiling `**` to `Math.pow()` which it shouldn't be doing since the operands in this case are `BigInt`.

**Comment by sebastiendan** [comment]
@acolytec3 Thanks for the feedback. I've pushed a repo ([here](https://github.com/sebastiendan/react-ts-nullcoalescing-exponentiation)) to reproduce the problem, and created an issue ([here](https://github.com/sebastiendan/react-ts-nullcoalescing-exponentiation/issues/1)) to describe more in depth the problem.

**Comment by acolytec3** [comment]
I responded on your repo issue how to resolve but will respond here as well in case others need this as may come up for other users of our libraries.  

If you update the browserslist field in package.json to something like this:

  "browserslist": [
    "chrome > 52",
    "opera > 39",
    "edge > 14",
    "firefox > 52",
    "safari > 10.1",
    "not dead",
    "not op_mini all"
  ],
The issue goes away. https://github.com/babel/babel/issues/13109 provides more detrail. You can probably use a more general browserlist setting like "last 2 versions" as well (depending on how old a browser you need to support). Yoiu can reference the [caniuse section on exponentation for further details](https://caniuse.com/?search=exponentiation).

**Comment by 0xboga** [comment]
I still struggled with this error using Nuxt2 and babel and finally worked with this config: ```babel: {
        presets: [
            '@babel/preset-env',
            '@babel/preset-typescript'
        ],
        plugins: [
            '@babel/plugin-proposal-optional-chaining',
            '@babel/plugin-proposal-nullish-coalescing-operator'
        ]
    }```
