### ISSUE TITLE
Noisy `client` logs

### ISSUE THREAD

**Issue by acolytec3** [ethereumjs/ethereumjs-monorepo#3087]
We've got some broken/noisy client logs and we should fix this:
Issue 1- New hardfork reached message is being logged on I guess every new block when we are at the head of the chain, like this:
![image](https://github.com/ethereumjs/ethereumjs-monorepo/assets/17355484/e6ca61d7-c3ff-45a7-a77b-704627a57505)

2) These Payload Stats logs should probably be debug or verbose level logs.  They're logged by the `CLConnectionManager` and they don't seem to provide any meaningful info for understanding basic node operations
![image](https://github.com/ethereumjs/ethereumjs-monorepo/assets/17355484/6c91854b-c483-43c3-96d8-e3ab832387bf)

**Comment by holgerd77** [comment]
Here are some traces for the HF back-and-forth switch:

```shell
[10-06|14:15:40] INFO [ CL ] ---------------------------------------
[10-06|14:15:42] INFO [ CL ] Executed blocks count=1 first=51763 hash=0x7403…6e5d baseFee=7 hardfork=shanghai last=51764 hash=0x051b…821a txs=2
Trace
    at EventEmitter.<anonymous> (ethereumjs-monorepo/packages/client/dist/src/blockchain/chain.js:125:21)
    at EventEmitter.emit (node:events:513:28)
    at Common.setHardfork (ethereumjs-monorepo/packages/common/dist/cjs/common.js:220:33)
    at Common.setHardforkBy (ethereumjs-monorepo/packages/common/dist/cjs/common.js:340:14)
    at Blockchain.checkAndTransitionHardForkByNumber (ethereumjs-monorepo/packages/blockchain/dist/cjs/blockchain.js:1043:21)
    at Chain.putBlocks (ethereumjs-monorepo/packages/client/dist/src/blockchain/chain.js:279:39)
    at async ethereumjs-monorepo/packages/client/dist/src/execution/vmexecution.js:219:13
    at async VMExecution.runWithLock (ethereumjs-monorepo/packages/client/dist/src/execution/vmexecution.js:91:27)
    at async Engine.forkchoiceUpdated (ethereumjs-monorepo/packages/client/dist/src/rpc/modules/engine.js:900:17)
[10-06|14:15:42] INFO [ CL ] ----------------------------------------------------------------
[10-06|14:15:42] INFO [ CL ] New hardfork reached 🪢 ! hardfork=mergeForkIdTransition block=0
[10-06|14:15:42] INFO [ CL ] ----------------------------------------------------------------
Trace
    at EventEmitter.<anonymous> (ethereumjs-monorepo/packages/client/dist/src/blockchain/chain.js:125:21)
    at EventEmitter.emit (node:events:513:28)
    at Common.setHardfork (ethereumjs-monorepo/packages/common/dist/cjs/common.js:220:33)
    at Common.setHardforkBy (ethereumjs-monorepo/packages/common/dist/cjs/common.js:340:14)
    at Blockchain.checkAndTransitionHardForkByNumber (ethereumjs-monorepo/packages/blockchain/dist/cjs/blockchain.js:1043:21)
    at ethereumjs-monorepo/packages/blockchain/dist/cjs/blockchain.js:392:36
    at async Blockchain.runWithLock (ethereumjs-monorepo/packages/blockchain/dist/cjs/blockchain.js:198:27)
    at async Blockchain._putBlockOrHeader (ethereumjs-monorepo/packages/blockchain/dist/cjs/blockchain.js:329:9)
    at async Blockchain.putBlock (ethereumjs-monorepo/packages/blockchain/dist/cjs/blockchain.js:267:9)
    at async Chain.putBlocks (ethereumjs-monorepo/packages/client/dist/src/blockchain/chain.js:286:13)
[10-06|14:15:42] INFO [ CL ] ------------------------------------------------------
[10-06|14:15:42] INFO [ CL ] New hardfork reached 🪢 ! hardfork=shanghai block=null
[10-06|14:15:42] INFO [ CL ] ------------------------------------------------------
[10-06|14:15:42] INFO [ CL ] Executed blocks count=1 first=51766 hash=0x8aa8…53ec baseFee=7 hardfork=shanghai last=51767 hash=0xe030…0601 txs=0
```
