### ISSUE TITLE
`verifyProof` seems inapplicable for a trie when only the on-chain `stateRoot`, `proofNodes`, and `key` are known

### ISSUE THREAD

**Issue by sunchengzhu** [ethereumjs/ethereumjs-monorepo#3176]
version: 
```js
"@ethereumjs/trie": "^6.0.1",
"@ethereumjs/util": "^9.0.1",
```

test code: 
```js
const { Trie } = require('@ethereumjs/trie');
const { bytesToUtf8, utf8ToBytes, equalsBytes, hexToBytes } = require('@ethereumjs/util');

const rootHash = '0xc109729691ff0d6c92f93d9ac2f2b95bf21d01aa6aa0148e45720216e240eab9';
const key = '0x7f3ad1bb474ddb6f61463f8e505b1223993d099ab9a557df67660f7078cf2a41';
const value = '0x162e';
const proofNodes = [
  "0xf8518080a036bb5f2fd6f99b186600638644e2f0396989955e201672f7e81e8c8f466ed5b980808080808080808080a072937edc8b3e6f63377600c48e0a998cece3d130ca60ea1814582fe817bdeb73808080",
  "0xe5a03ca8639a4722e15ebc4948282d79ef2b21c42948160058cbe4cf431edf41f61b8382162e"
];

await myVerifyProof(rootHash, key, value, proofNodes);

async function myVerifyProof(rootHash, key, value, proofNodes) {
  const root = hexToBytes(rootHash);
  const proof = proofNodes.map(node => hexToBytes(node));

  try {
    const trie = new Trie({ root: root });
    const verifiedValue = await trie.verifyProof(root, hexToBytes(key), proof);
    if (equalsBytes(verifiedValue, hexToBytes(value))) {
      console.log('Proof valid:', verifiedValue.toString());
    } else {
      console.log('Invalid proof or value');
    }
  } catch (error) {
    console.error('Proof verification failed:', error);
  }
}
   
```

`rootHash` and `proofNode` are returned from: 
``` bash
curl -sS -X POST \
  https://eth-sepolia.g.alchemy.com/v2/${Alchemy_API_Key} \
  -H 'Content-Type: application/json' \
  -d '{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["0x49a2f8", false],
    "id": 1
 }' | jq '.result.stateRoot'
```
```bash
curl -sS -X POST \
  https://eth-sepolia.g.alchemy.com/v2/${Alchemy_API_Key} \
  -H 'Content-Type: application/json' \
  -d '{
  "jsonrpc":"2.0",
  "method":"eth_getProof",
  "params": ["0xD907B959E9de1852D6dDdd8B5BF26A6EC54387F1", ["0x7f3ad1bb474ddb6f61463f8e505b1223993d099ab9a557df67660f7078cf2a41"], "latest"],
  "id":2
}' | jq '.result.storageProof'
```

result: 
```
Proof verification failed: Error: Invalid proof provided
    at Trie.verifyProof (/Users/sunchengzhu/project/axon-test/node_modules/@ethereumjs/trie/dist/cjs/trie.js:809:23)
    at async myVerifyProof (/Users/sunchengzhu/project/axon-test/test/rpc/eth_getProof.test.js:38:27)
    at async Context.<anonymous> (/Users/sunchengzhu/project/axon-test/test/rpc/eth_getProof.test.js:25:1)
```
[Do I have to use a DB?](https://github.com/ethereumjs/ethereumjs-monorepo/blob/f9525af55b4c2068a003e8035184913c0adcd980/packages/trie/src/trie.ts#L966-L967)
I spent a lot of time reading the code and documentation but couldn't find a solution. If feasible, could you provide me with an example? Thank you very much.

**Comment by jochem-brouwer** [comment]
This works:

```typescript
import { RLP } from '@ethereumjs/rlp'
import { equalsBytes, hexToBytes } from 'ethereum-cryptography/utils.js'
import { describe, it } from 'vitest'

import { Trie } from '../src/index.js'

describe('verify proof', () => {
  const rootHash = '0x55b990cc1a1e53034bf577f5060958fc716a051a343f575d8e8b9f80a228c16d'
  const key = '0x7f3ad1bb474ddb6f61463f8e505b1223993d099ab9a557df67660f7078cf2a41'
  const value = '0x162e'
  const proofNodes = [
    '0xf8518080a036bb5f2fd6f99b186600638644e2f0396989955e201672f7e81e8c8f466ed5b980808080808080808080a072937edc8b3e6f63377600c48e0a998cece3d130ca60ea1814582fe817bdeb73808080',
    '0xe5a03ca8639a4722e15ebc4948282d79ef2b21c42948160058cbe4cf431edf41f61b8382162e',
  ]

  it('should verify', async () => {
    const root = hexToBytes(rootHash)
    const proof = proofNodes.map((node) => hexToBytes(node))
    const proofTrie = await Trie.create({ useKeyHashing: true })
    try {
      const verifiedValue = await proofTrie.verifyProof(root, hexToBytes(key), proof)
      if (equalsBytes(RLP.decode(verifiedValue!), hexToBytes(value))) {
        console.log('Proof valid:', verifiedValue!.toString())
      } else {
        console.log('Invalid proof or value')
      }
    } catch (error) {
      console.error('Proof verification failed:', error)
    }
  })
})

```

Note that you should use `useKeyHashing: true` for the trie, and the returned values from the trie are actually RLP-encoded, so in order to get the actual value one has to decode that one as well.

Side note: your API keys for alchemy are compromised in your issue description.
