### ISSUE TITLE
client: AccountFetcher Crashes when Receiving a Rejection from an Unsynced Peer

### ISSUE THREAD

**Issue by scorbajio** [ethereumjs/ethereumjs-monorepo#3221]
Currently, when the EthereumJS client requests accounts using the snap sync `getAccountRange` API call from a Geth client that is not yet synced, it crashes when handling the rejection response:
```
[01-05|18:29:15] INFO -----------------------------------
[01-05|18:29:15] INFO Snapsync: running accountFetch=true 
[01-05|18:29:15] INFO -----------------------------------
TypeError: Cannot read properties of undefined (reading 'hash')
    at AccountFetcher.verifyRangeProof (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/accountfetcher.js:161:109)
    at AccountFetcher.request (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/accountfetcher.js:240:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-01-06T01:29:15.814Z client:AccountFetcher Failure - Re-enqueuing job index=1 origin=0x0041…c6a7 limit=0x0083…8d4d from peer id=98169dcc (error: Error: InvalidAccountRange: TypeError: Cannot read properties of undefined (reading 'hash')).
```
The `AccountFetcher` and other snap sync fetchers should be able provide a custom error message instead of crashing.

**Comment by holgerd77** [comment]
@scorbajio is this still an issue or can it be closed here (in doubt close if you feel the issue is not helpful anymore)?
