### ISSUE TITLE
client: TrieNodeFetcher crashes due to undefined pathString

### ISSUE THREAD

**Issue by scorbajio** [ethereumjs/ethereumjs-monorepo#3244]
During the heal phase of snap sync, the `TrieNodeFetcher` crashes due to an `undefined` `pathString`:
```
2024-01-19T01:13:27.794Z client:TrieNodeFetcher All requests for current heal phase have been filled
2024-01-19T01:13:27.795Z client:TrieNodeFetcher Stored accountTrie with root actual=3372b525c0074182d1743177ce733675dc7262fc0fca13fd664e99b5ca0d5ec3 expected=3372b525c0074182d1743177ce733675dc7262fc0fca13fd664e99b5ca0d5ec3
2024-01-19T01:13:27.795Z client:TrieNodeFetcher At start of store phase
2024-01-19T01:13:27.797Z client:TrieNodeFetcher TypeError: Cannot read properties of undefined (reading 'split')
    at TrieNodeFetcher.store (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/trienodefetcher.js:110:63)
    at _write (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:275:32)
    at Writable.writev [as _writev] (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:306:24)
    at doWrite (node:internal/streams/writable:409:12)
    at clearBuffer (node:internal/streams/writable:564:5)
    at onwrite (node:internal/streams/writable:464:7)
    at Writable._write (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:278:17)
2024-01-19T01:13:27.797Z client:TrieNodeFetcher At start of store phase
2024-01-19T01:13:27.798Z client:TrieNodeFetcher TypeError: Cannot read properties of undefined (reading 'split')
    at TrieNodeFetcher.store (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/trienodefetcher.js:110:63)
    at _write (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:275:32)
2024-01-19T01:13:27.799Z client:TrieNodeFetcher At start of store phase
2024-01-19T01:13:27.800Z client:TrieNodeFetcher TypeError: Cannot read properties of undefined (reading 'split')
    at TrieNodeFetcher.store (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/trienodefetcher.js:110:63)
    at _write (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:275:32)
2024-01-19T01:13:27.800Z client:TrieNodeFetcher At start of store phase
2024-01-19T01:13:27.800Z client:TrieNodeFetcher TypeError: Cannot read properties of undefined (reading 'split')
    at TrieNodeFetcher.store (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/trienodefetcher.js:110:63)
    at _write (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:275:32)
2024-01-19T01:13:27.800Z client:TrieNodeFetcher At start of store phase
2024-01-19T01:13:27.801Z client:TrieNodeFetcher TypeError: Cannot read properties of undefined (reading 'split')
    at TrieNodeFetcher.store (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/trienodefetcher.js:110:63)
    at _write (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:275:32)
2024-01-19T01:13:27.801Z client:TrieNodeFetcher At start of store phase
2024-01-19T01:13:27.806Z client:TrieNodeFetcher TypeError: Cannot read properties of undefined (reading 'split')
    at TrieNodeFetcher.store (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/trienodefetcher.js:110:63)
    at _write (/home/indigoomega021/code/projects/eth/ethjs-lodestar/ethereumjs-monorepo/packages/client/dist/src/sync/fetcher/fetcher.js:275:32)
```
To recreate the issue, run the ethjs snap sync devnet. For help, see [this PR](https://github.com/ChainSafe/lodestar-quickstart/pull/28).

**Comment by scorbajio** [comment]
Fixed by #3252.
