### ISSUE TITLE
Running geth README example compromises geth database

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#697]
When I run the geth iterator example from the README with geth ``1.8.14-stable`` and having synced some blocks with:

```shell
geth --datadir="./test-chain" --syncmode="full"
```

...I am ending up with a compromised geth database, so running the geth sync command from above again gives me the following error stack (shortened):

```shell
INFO [08-29|11:45:56.103] Initialising Ethereum protocol           versions="[63 62]" network=1
WARN [08-29|11:45:56.104] Head state missing, repairing chain      number=0 hash=d4e567…cb8fa3
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x447e3fa]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core/types.(*Block).Root(...)
	/private/tmp/ethereum-20180829-39282-1s822bo/build/_workspace/src/github.com/ethereum/go-ethereum/core/types/block.go:315
github.com/ethereum/go-ethereum/core.(*BlockChain).repair(0xc000018000, 0xc0004e61e0, 0xc0004e6248, 0x4)
	/private/tmp/ethereum-20180829-39282-1s822bo/build/_workspace/src/github.com/ethereum/go-ethereum/core/blockchain.go:429 +0x4a
github.com/ethereum/go-ethereum/core.(*BlockChain).loadLastState(0xc000018000, 0x0, 0xc0002d4360)
```

This is also happening when removing the ``iterator(...)`` call from the example code.

**Comment by holgerd77** [comment]
Along the latest README updates I have removed the Geth example since it was outdated anyhow, will close here.
