### ISSUE TITLE
Client Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-monorepo#991]
```shell
$ ethereumjs
INFO [06-01|17:47:12] Data directory:/ethereumjs/chaindata
INFO [06-01|17:47:12] Initializing Ethereumjs client...
INFO [06-01|17:47:12] Fast sync mode
INFO [06-01|17:47:12] Connecting to network: mainnet
INFO [06-01|17:47:12] Latest local block: number=756736 td=4760424299033370527 hash=b04c06a9...
INFO [06-01|17:47:12] Synchronizing blockchain...
INFO [06-01|17:47:12] Started rlpx server.
INFO [06-01|17:47:12] Started libp2p server.
INFO [06-01|17:47:14] Listener up transport=rlpx url=enode://196b9d06b0c153ec8ed78455c7ecb67d661f5279569d0a1ea9ec3afe8d670692d0da57ea781902e14409364f065c6c275c63f9b57e446fc482fa24be1fe4ed76@[::]:30303
INFO [06-01|17:47:14] Listener up transport=libp2p url=/p2p-circuit/ipfs/Qmf63v65ySQNuXXmomJb2uS3TTPPkYmCb8BAJD5Q5Dguc7
INFO [06-01|17:47:14] Listener up transport=libp2p url=/p2p-circuit/ip4/127.0.0.1/tcp/50580/ws/ipfs/Qmf63v65ySQNuXXmomJb2uS3TTPPkYmCb8BAJD5Q5Dguc7
INFO [06-01|17:47:14] Listener up transport=libp2p url=/ip4/127.0.0.1/tcp/50580/ws/ipfs/Qmf63v65ySQNuXXmomJb2uS3TTPPkYmCb8BAJD5Q5Dguc7
INFO [06-01|17:47:14] Started eth service.
ERROR [06-01|17:48:44] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:431:19)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Socket.Writable.write (_stream_writable.js:309:11)
    at Peer._sendMessage (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:406:22)
    at Peer._sendPong (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:441:14)
    at Peer._handleMessage (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:349:22)
    at Peer._parsePacketContent (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:222:34)
    at Socket.<anonymous> (/ethereumjs-client/node_modules/ethereumjs-devp2p/dist/rlpx/peer.js:162:31)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
```

This error is thrown repeatedly during a normal sync run and needs some further investigation.

**Comment by holgerd77** [comment]
Fixed by #1075, will close.
